####  Build the MCP server  ####################################################

FROM python:3.10-slim AS server-mcp
WORKDIR /app

# Copy project files
COPY requirements.txt ./
COPY src/server ./server

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

####  Run the server  ##########################################################

# Conditionally instrument OpenTelemetry with entrypoint script
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]

# Set environment variables
ENV FASTMCP_HOST=0.0.0.0
ENV FASTMCP_PORT=4096
ENV FASTMCP_SERVER_TRANSPORT=http
ENV OTEL_SERVICE_NAME=esrs-server-mcp

# Run the MCP server
CMD ["python", "-m", "server.fastmcp"]
EXPOSE 4200